"Steam/SubPanelSubscribeReview.r"
{
	"InfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoLabel"
		"xpos"		"48"
		"ypos"		"28"
		"wide"		"390"
		"tall"		"48"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Steam_SubscribeReviewInfo"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"48"
		"ypos"		"94"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"name:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"48"
		"ypos"		"114"
		"wide"		"110"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"credit card type:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"48"
		"ypos"		"134"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"number:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"48"
		"ypos"		"154"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"expiration:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label6"
	{
		"ControlName"		"Label"
		"fieldName"		"Label6"
		"xpos"		"48"
		"ypos"		"174"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"street address:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label7"
	{
		"ControlName"		"Label"
		"fieldName"		"Label7"
		"xpos"		"48"
		"ypos"		"194"
		"wide"		"100"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"city:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label8"
	{
		"ControlName"		"Label"
		"fieldName"		"Label8"
		"xpos"		"48"
		"ypos"		"214"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"postcode:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label9"
	{
		"ControlName"		"Label"
		"fieldName"		"Label9"
		"xpos"		"48"
		"ypos"		"234"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"state:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Label10"
	{
		"ControlName"		"Label"
		"fieldName"		"Label10"
		"xpos"		"48"
		"ypos"		"252"
		"wide"		"64"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"country:"
		"textAlignment"		"west"
		"dulltext"		"1"
	}
	"Data2"
	{
		"ControlName"		"Label"
		"fieldName"		"Data2"
		"xpos"		"180"
		"ypos"		"94"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		" "
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data3"
	{
		"ControlName"		"Label"
		"fieldName"		"Data3"
		"xpos"		"180"
		"ypos"		"114"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"American Express"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data4"
	{
		"ControlName"		"Label"
		"fieldName"		"Data4"
		"xpos"		"180"
		"ypos"		"134"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data5"
	{
		"ControlName"		"Label"
		"fieldName"		"Data5"
		"xpos"		"180"
		"ypos"		"154"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"06/2002"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data6"
	{
		"ControlName"		"Label"
		"fieldName"		"Data6"
		"xpos"		"180"
		"ypos"		"174"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data7"
	{
		"ControlName"		"Label"
		"fieldName"		"Data7"
		"xpos"		"180"
		"ypos"		"194"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data8"
	{
		"ControlName"		"Label"
		"fieldName"		"Data8"
		"xpos"		"180"
		"ypos"		"214"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data9"
	{
		"ControlName"		"Label"
		"fieldName"		"Data9"
		"xpos"		"180"
		"ypos"		"234"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
	"Data10"
	{
		"ControlName"		"Label"
		"fieldName"		"Data10"
		"xpos"		"180"
		"ypos"		"254"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"United States"
		"textAlignment"		"west"
		"dulltext"		"0"
	}
}
